import {
  AlarmClock,
  Baby,
  Banknote,
  BarChart3,
  Bath,
  BedDouble,
  Bike,
  BookOpen,
  BriefcaseBusiness,
  Bus,
  CakeSlice,
  Car,
  Cat,
  Circle,
  ClipboardList,
  Cloud,
  Coffee,
  Coins,
  CreditCard,
  Dumbbell,
  Ellipsis,
  Film,
  Fish,
  Flame,
  Gamepad2,
  Gift,
  GraduationCap,
  HandCoins,
  Handshake,
  HeartPulse,
  Hospital,
  House,
  Landmark,
  Laptop,
  Lightbulb,
  MapPin,
  Martini,
  MessageCircle,
  Monitor,
  Music,
  Package,
  Palette,
  PawPrint,
  Pencil,
  Pill,
  Plane,
  Pizza,
  Plug,
  Receipt,
  Repeat2,
  Rocket,
  Scissors,
  Search,
  ShoppingBag,
  ShoppingBasket,
  ShoppingCart,
  Shirt,
  Smartphone,
  Sparkles,
  Stethoscope,
  Store,
  Tag,
  Train,
  TreePine,
  Trophy,
  Tv,
  Utensils,
  Wallet,
  WashingMachine,
  Wifi,
  Wrench,
  type LucideIcon,
} from "lucide-react";

const categoryIconMap: Record<string, LucideIcon> = {
  alarm: AlarmClock,
  baby: Baby,
  banknote: Banknote,
  chart: BarChart3,
  bath: Bath,
  bed: BedDouble,
  bike: Bike,
  book: BookOpen,
  briefcase: BriefcaseBusiness,
  bus: Bus,
  cake: CakeSlice,
  car: Car,
  cat: Cat,
  circle: Circle,
  clipboard: ClipboardList,
  cloud: Cloud,
  coffee: Coffee,
  coins: Coins,
  "credit-card": CreditCard,
  dumbbell: Dumbbell,
  ellipsis: Ellipsis,
  film: Film,
  fish: Fish,
  flame: Flame,
  gamepad: Gamepad2,
  gift: Gift,
  graduation: GraduationCap,
  "hand-coins": HandCoins,
  handshake: Handshake,
  "heart-pulse": HeartPulse,
  hospital: Hospital,
  house: House,
  landmark: Landmark,
  laptop: Laptop,
  lightbulb: Lightbulb,
  "map-pin": MapPin,
  martini: Martini,
  message: MessageCircle,
  monitor: Monitor,
  music: Music,
  package: Package,
  palette: Palette,
  paw: PawPrint,
  pencil: Pencil,
  pill: Pill,
  plane: Plane,
  pizza: Pizza,
  plug: Plug,
  receipt: Receipt,
  repeat: Repeat2,
  rocket: Rocket,
  scissors: Scissors,
  search: Search,
  "shopping-bag": ShoppingBag,
  "shopping-basket": ShoppingBasket,
  "shopping-cart": ShoppingCart,
  shirt: Shirt,
  smartphone: Smartphone,
  sparkles: Sparkles,
  stethoscope: Stethoscope,
  store: Store,
  tag: Tag,
  train: Train,
  tree: TreePine,
  trophy: Trophy,
  tv: Tv,
  utensils: Utensils,
  wallet: Wallet,
  "washing-machine": WashingMachine,
  wifi: Wifi,
  wrench: Wrench,

  // Valores antigos ou de compatibilidade.
  cart: ShoppingCart,
  food: Utensils,
  health: HeartPulse,
  education: GraduationCap,
  leisure: Gamepad2,
  other: Circle,
};

type CategoryIconProps = {
  name?: string | null;
  size?: number;
  strokeWidth?: number;
  className?: string;
};

export function CategoryIcon({
  name,
  size = 20,
  strokeWidth = 1.8,
  className,
}: CategoryIconProps) {
  const Icon = categoryIconMap[name ?? "other"] ?? Circle;

  return (
    <Icon
      aria-hidden="true"
      className={className}
      size={size}
      strokeWidth={strokeWidth}
    />
  );
}